let harina = "2 tazas de harina";
let levadura = "1 cucharada de levadura";
let azucar = "1 cucharada de azucar";
let sal="20 gramos de sal";
let agua = "1 taza de agua";
let aceite = "2 rociadas de aceite";
let mantequilla = "1 cuchara de mantequilla";
let salsamarinera = "1 taza de salsa marinara";
let quesomozarella="6 onzas de queso";
